#!/bin/bash



cp val_dir-composition_3_17_POSCARS.cfg DFT.cfg
cp val_dir-composition_3_17_POSCARS.cfg MLIP.cfg

grep -A1 "Energy" DFT.cfg >> DFT.energy

/cephfs/home/amikhailova/year_2022/Singapore/dataset/CuAu/mlp calculate_efs final.mtp MLIP.cfg 

grep -A1 "Energy" MLIP.cfg  >> MLIP.energy
